### ISSUE TITLE
Todo List (large horizontal)

### ISSUE THREAD

**Issue by leslie-alldridge** [kakapo-2018/Personal-Dashboard#25]
- [x] add, edit, delete todos
- [x] tick off todos 
- [ ] filter between work and personal todos  - spoke to PO and we will do a filter as a stretch goal
